# Generated by Django 2.2.16 on 2022-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220201_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this work', related_name='genres', to='reviews.Genre'),
        ),
    ]
